@startuml

class Answer {
int answerId
string aText
bool isCorrect
}

class Category {
int categoryId
string Name
ICollection<Question> questions
}

class Course {
int courseId
string name
string description
Professor responsible
int maxStudents
ICollection<Category> categories
ICollection<Subscription> subscriptionRequests
ICollection<Quizz> quizzes
ICollection<Question> questions
}

class Professor {
Course course
}

'=banque de questions d'un cours :
class Question {
int questionId
'=énoncé :
string qText
'=type de question : une seule ou plusieurs réponses
bool type
ICollection<Answer> possibleAnswers
ICollection<Category> categories
}

class Quizz {
int quizzId
string title
DateTime start
DateTime end
ICollection<Question> questions
ICollection<Test> tests
bool visible()
bool editable()
}

class QuizzQuestion {
int questionId
int quizzId
Quizz quizz
Question question
'=valeur de la question :
int questionValue
}

class Student {
ICollection<Course> courses
ICollection<Test> tests
'= liste des scores obtenus pour les tests
scoreSheet()
}

class Subscription {
Course course
Student student
bool active
bool validated
}

class Test {
int testId
Student student
Quizz quizz
Dictionary<Question, List<Answer>> studentAnswers
int score()
bool visible()
bool editable()
}

abstract class User {
int UserId
string surname
string name
string email
string password
}

User <|-- Student
User <|-- Professor
Student " 1 " <--> " * " Subscription
Course " 1 " <--> " * " Subscription
Professor " 1 " <--> " * " Course
Course " 1 " <--> " * " Quizz
Course " 1 " <--> " * " Question
Quizz " * " <--> " * " Question
Question " 1 " <--> " * " Answer
Question " 1 " <--> " 1...* " Category
Quizz " 1 " <--> " 1 " Test
Student " 1 " <--> " * " Test
Test " 1 " <--> " * " Answer

@enduml
